name: predict-loan-default
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - jupyter
    - papermill
    - nb_black
    - numpy
    - pandas
    - pandas-profiling[notebook,html]
    - scikit-learn
    - matplotlib
    - seaborn
    - imbalanced-learn
    - yellowbrick
